---
kind: pipeline
type: docker
name: build

steps:
- name: build
  image: node:16-bullseye
  environment:
    DRONE_TAG: ${DRONE_TAG}
  commands:   
    - |
      if [ -z ${DRONE_TAG+x} ]; then export DRONE_TAG=development; fi
      sed -i -E \"s/version: \\\"(.*)\\\"/version: \\\"$DRONE_TAG\\\"/g\" src-ui/src/environments/environment.prod.ts

      cd src-ui
      npm ci --no-optional
      ./node_modules/.bin/ng build --configuration production
      
      cd ..

      cp paperless.conf.example paperless.conf
      tar -czvf --exclude=*/tests/* release.tgz src/ requirements.txt paperless.conf gunicorn.conf.py

- name: gitea_release
  image: plugins/gitea-release
  settings:
    api_key: 
      from_secret: gitea_api_key
    base_url: https://git.markus-kling.net/
    file_exists: overwrite
    files: 
     - release.tgz

trigger:
  event:
  - tag
